ViewModels/TagViewModel.cs
using System.Linq;
using System.Collections.Generic;

namespace FusekiC
{
    public class TagViewModel
    {
        public TagViewModel(string tags, string highlightTag)
        {
            Tags = tags.Split(',').ToList();
            HighlightTag = highlightTag;
        }

        public TagViewModel(List<Tag> tags, string highlightTag)
        {
            Tags = tags.Select(ee=>ee.Name).ToList();
            HighlightTag = highlightTag;
        }

        public List<string> Tags { get; set; }
        public string HighlightTag { get; set; }
    }
}

Controllers/PublicationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Accord.MachineLearning;
using Accord.Statistics.Filters;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGeneration;
using static FusekiC.Helpers;

namespace FusekiC
{
    [Authorize]
    public class PublicationController : Controller
    {
        private Publisher Publisher { get; set; }
        private Renderer Renderer { get; set; }
        private ConsoleLogger Logger { get; set; }
        private Settings Settings { get; set; }
        private PublishConfiguration PublishConfiguration { get; set; }
        public PublicationController(Renderer renderer, ConsoleLogger logger, Settings settings, PublishConfiguration pc)
        {
            Logger = logger;
            Settings = settings;
            Renderer = renderer ?? throw new ArgumentNullException(nameof(renderer));
            PublishConfiguration = pc;
            Publisher = new Publisher(Renderer, logger, Settings, PublishConfiguration);
        }

        [HttpGet("/listpublications")]
        public IActionResult Index()
        {
            using (var db = new FusekiContext())
            {
                var pubs = db.Publications.OrderByDescending(el => el.Id).ToList();
                var model = new PublicationListModel(pubs);
                ViewData["Title"] = $"Publications";
                return View("PublicationList", model);
            }
        }

        [HttpPost("/publish")]
        public IActionResult Publish()
        {
            var model = new PublicationResultModel();

            var publishResult = Publisher.Publish();

            var publication = new Publication();
            publication.ArticleCount = publishResult.Count;
            publication.PublicationTime = DateTime.Now;
            using (var db = new FusekiContext())
            {
                db.Add(publication);
                db.SaveChanges();
            }
            model.Publication = publication;
            ViewData["Title"] = $"PublicationResult";
            return View("PublicationResult", model);
        }

        [HttpPost("/partition")]
        public IActionResult Partition(int partitionCount)
        {
            //var partitioner = new Partitioner<Article>((a, b) => Comparators.GetLengthDistance(a, b), (a, b) => Comparators.ArticleKeyLookup(a, b));
            var partitioner = new Partitioner<Article>((a, b) => Comparators.GetTagCommonality(a, b), (a, b) => Comparators.ArticleKeyLookup(a, b));

            using (var db = new FusekiContext())
            {
                var articles = db.Articles.Where(el => el.Published == true)
                    .Include(el => el.Tags).ToList();
                var r = new Random();
                articles = articles.OrderBy(el => r.NextDouble()).ToList();
                var partitiondata = partitioner.GetPartitions(partitionCount, articles);
                var model = new ArticlePartitionModel(partitiondata);
                return View("ArticlePartitions", model);
            }
        }

        //[HttpPost("/partition3")]
        //public IActionResult Partition3(int partitionCount)
        //{
        //    using (var db = new FusekiContext())
        //    {
        //        var articles = db.Articles.Where(el => el.Published == true)
        //            .Include(el => el.Tags).Take(3).ToList();
        //        //get a tag vector for each article.

        //        var allTags = new HashSet<string>();

        //        //TODO: What happens if we remove all tags which only occur once.
        //        foreach (var article in articles)
        //        {
        //            foreach (var tag in article.Tags)
        //            {
        //                allTags.Add(tag.Name);
        //            }
        //        }

        //        var newAllTags = new HashSet<string>();
        //        foreach (var t in allTags)
        //        {
        //            var relatedArticles = db.Articles.Where(el => el.Tags.Select(tag => tag.Name).Contains(t));
        //            if (relatedArticles.Count() > 1)
        //            {
        //                newAllTags.Add(t);
        //            }
        //        }

        //        allTags = newAllTags;

        //        var allTagsOrdered = allTags.OrderBy(el => el);

        //        var obs = new List<List<double>>();
        //        var dict = new Dictionary<string, object>();

        //        foreach (var article in articles)
        //        {
        //            var articleTags = article.Tags.Select(el => el.Name);
        //            var vector = new List<double>();
        //            foreach (var tag in allTagsOrdered)
        //            {
        //                if (articleTags.Contains(tag))
        //                {
        //                    vector.Add(1);
        //                }
        //                else
        //                {
        //                    vector.Add(0);
        //                }
        //            }
        //            obs.Add(vector);
        //        }

        //        var n = obs.Count;
        //        var m = obs[0].Count;

        //        double[,] test = new double[n, m];

        //        var ii = 0;
        //        foreach (var el in obs)
        //        {
        //            var jj = 0;
        //            foreach (var item in el)
        //            {
        //                test[ii, jj] = item;
        //                jj++;
        //            }
        //            ii++;
        //        }
        //        //TODO: confirm this is converting data correctly.

                
        //        alglib.clusterizerstate s;
        //        alglib.ahcreport rep;
        //        int[] cidx;
        //        int[] cz;
        //        alglib.clusterizercreate(out s);
        //        alglib.clusterizersetpoints(s, test, 2);
        //        var q = test.ToString();
        //        alglib.clusterizersetahcalgo(s, 0);
        //        alglib.clusterizerrunahc(s, out rep);
        //        var res = alglib.clusterizergetkclusters(rep, partitionCount, out cidx, out cz);
        //        //todo: is there a way to convert a dendogram to N clusters? Or just keep it that way?
        //        return null;
        //    }
        //}


        [HttpPost("/partition2")]
        public IActionResult Partition2(int partitionCount)
        {
            using (var db = new FusekiContext())
            {
                var articles = db.Articles.Where(el => el.Published == true)
                    .Include(el => el.Tags).Take(20).ToList();
                //get a tag vector for each article.

                var allTags = new HashSet<string>();

                //TODO: What happens if we remove all tags which only occur once.
                foreach (var article in articles)
                {
                    foreach (var tag in article.Tags)
                    {
                        allTags.Add(tag.Name);
                    }
                }

                var newAllTags = new HashSet<string>();
                foreach (var t in allTags)
                {
                    var relatedArticles = db.Articles.Where(el => el.Tags.Select(tag => tag.Name).Contains(t));
                    if (relatedArticles.Count() > 1)
                    {
                        newAllTags.Add(t);
                    }
                }

                allTags = newAllTags;

                var allTagsOrdered = allTags.OrderBy(el => el);

                var obs = new List<List<double>>();
                var dict = new Dictionary<string, object>();

                foreach (var article in articles)
                {
                    var articleTags = article.Tags.Select(el => el.Name);
                    var vector = new List<double>();
                    foreach (var tag in allTagsOrdered)
                    {
                        if (articleTags.Contains(tag))
                        {
                            vector.Add(1);
                        }
                        else
                        {
                            vector.Add(0);
                        }
                    }
                    obs.Add(vector);
                }

                var vecvec = obs.Select(el => el.ToArray()).ToArray();

                var kmeans = new KMeans(k: partitionCount);

                var clusters = kmeans.Learn(vecvec);
                dict["Kmeans Error"] = kmeans.Error;
                dict["dimensionality"] = kmeans.Dimension;
                dict["Iterations"] = kmeans.Iterations;
                dict["MaxIterations"] = kmeans.MaxIterations;
                dict["Tolerance"] = kmeans.Tolerance;


                int[] labels = clusters.Decide(vecvec);
                //labels is array[articleId] => partitionNumber
                var ii = 0;
                var psets = new List<PartitionSet<Article>>();

                //this is totally fake. TODO: refactor these to be dumber - no need to have comparators etc.
                var dm = new DistanceMetrics<Article>((a, b) => Comparators.GetTagCommonality(a, b), (a, b) => Comparators.ArticleKeyLookup(a, b));
                while (ii < partitionCount)
                {
                    //TODO: is accord zero indexed?
                    psets.Add(new PartitionSet<Article>(dm, ii));
                    ii++;
                }
                var index = 0;
                foreach (var l in labels)
                {
                    var article = articles[index];
                    index++;

Pages/Shared/ActionResult.cshtml


@model ActionResultModel
<h2>Result:</h2>

@Html.Raw(Model.GetResult())

<br /><a href="@Model.NextLink">@Model.NextLinkDescription</a>

Pages/Shared/ArticlePartitions.cshtml
@model ArticlePartitionModel

<h2>Article Partition</h2>


<table>
    @foreach (var k in Model.Data.Keys)
    {

        <tr>
            <td>
                @k
            </td>
            <td>
                @Model.Data[k]
            </td>
        </tr>

    }
</table>

@foreach (var set in Model.Partitions)
{   <br />
    <table>
        <tr>
            <td colspan="10">
                <h3>Partition @set.Number</h3>
                Avg Distance: @set.AverageDistance()
            </td>
        </tr>
        @foreach (var article in set.Items.OrderBy(el=>el.Title))
        {
            <tr>
                <td style="width:200px !important;" class="nb">@article.Title</td>
                @foreach (var tag in Model.TagLists[set])
                {
                    @if (article.Tags.Select(el => el.Name).Contains(tag))
                    {
                        <td class="nb" style="border:1px dashed black;">@tag</td>
                    }
                    else
                    {
                        <td style="border:1px dashed black;"></td>
                    }
                }
            </tr>
        }
        </table>
    }

Pages/Shared/DeleteButton.cshtml
@model ArticleModel
@{ 
    var text = "";
    if (Model.Deleted)
    {
        text = "Undelete";
    }
    else
    {
        text = "Delete";
    }
}
<button class="btn btn-primary delete" articleId="@Model.Id">@text</button>

Pages/Shared/EditArticle.cshtml
@model ArticleModel

<div class="pageData" kind="editArticle"></div>

    <form method="post"
          action="/article/update">
        <button type="submit" class="btn btn-primary">Save</button>
        <hr />
        @Html.EditorFor(m => m.Title, new { htmlAttributes = new { @class = "title-editor" } })
        <hr />

        <hr />

        @Html.TextAreaFor(m => m.Body, 20, 100, new { })
        <hr />
        @Html.EditorFor(m => m.Tags, new { htmlAttributes = new { @class = "tag-editor" } })
        <input type="hidden" name="id" value="@Model.Id" />

        <hr />
        <button type="submit" class="btn btn-primary">Save</button>
    </form>

Pages/Shared/ImageControl.cshtml
@model Image
<td>
    <form method="post" action="/image/delete">
        <input type="hidden" name="id" value="@Model.Id" />
        <input class="btn" type="submit" value="Delete" />
    </form>
    <form method="post" action="/image/settags">
        <input type="hidden" name="id" value="@Model.Id" />
        <input type="text" name="tagLine" value="@Model.GetTagString()" />
        <input class="btn" type="submit" value="Set Tags" />
    </form>
</td>

Pages/Shared/Login.cshtml
@model LoginModel

    <form action="/account/login" method="POST">
        @Html.EditorFor(m => m.Username)
        @Html.PasswordFor(m => m.Password)
        @Html.DisplayFor(m => m.Error)
        <button type="submit" class="btn btn-primary">Login</button>
    </form>

Pages/Shared/PublicationList.cshtml
@model PublicationListModel

<h2>Publications</h2>

<ul>
    <table>
        <tr>
            <th>Publication</th>
            <th>Articles</th>
            <th>Date</th>
        </tr>
        @foreach (var publication in (Model.Publications))
        {
            <tr>
                <td>
                    @publication.Id
                </td>
                <td>@publication.ArticleCount</td>

                <td>
                    @publication.PublicationTime
                </td>
            </tr>
        }
    </table>
</ul>

Pages/Shared/PublicationResult.cshtml
@model PublicationResultModel

<h2>Published</h2>

id: @Model.Publication.Id

<br />count: @Model.Publication.ArticleCount
<br />time: @Model.Publication.PublicationTime

Pages/Shared/PublishButton.cshtml
@model ArticleModel
@{
    var text = "";
    if (Model.Published)
    {
        text = "Unpublish";
    }
    else
    {
        text = "Publish";
    }
}
<button class="btn btn-primary publish" articleId="@Model.Id">@text</button>

Pages/Shared/RelatedArticle.cshtml
@model RelatedArticle

<div class="relatedarticle">
    @Html.ActionLink(@Model.Article.Title, "ViewArticle", "Admin", new { title = Model.Article.Title })
</div>

Pages/Shared/TagList.cshtml
@model MetatagListModel

<h2>List Tags by: @Model.Name</h2>

<ul>
    <table>
        <tr>
            <th>Tag</th>
            <th>Articles</th>
            <th>Updated</th>
        </tr>
        @foreach (var metatag in (Model.Metatags))
        {
            <tr>
                <td>
                    @Html.ActionLink(metatag.Name, "Tag", "Admin", new { name = metatag.Name })

                </td>
                <td>
                    @metatag.Articles.Count
                </td>

                <td class="nb">
                    @metatag.Updated.ToString(MvcHelpers.DateFormat)
                </td>

            </tr>
        }
    </table>
</ul>
<div class="navigation">
    @Html.ActionLink("List", "List", "Admin")
    @Html.ActionLink("ListAll", "ListAll", "Admin")
    @Html.ActionLink("TagList", "TagList", "Admin")
    @Html.ActionLink("Create", "CreateArticle", "Admin")
</div>

Pages/Shared/Upload.cshtml
<form action="/image/upload/"
      enctype="multipart/form-data"
      method="post">
    <dl>
        <dt>
            <label for="UploadFileModel">File</label>
        </dt>
        <dd>
            <input id="image" type="file" name="image" />
            tags: <input name="tagLine" type="text" value="" />
            override-name: <input id="name" type="text" name="filename" />
        </dd>
    </dl>

    <input class="btn" type="submit" value="Upload" />

    <div style="margin-top:15px">
        <output name="result"></output>
    </div>
</form>

Pages/Shared/ViewImages.cshtml
@model ViewImagesModel

<h2>@Model.Term</h2>

<table class="images">
    <tr>
        <td>id</td>
        <td>filename</td>
        <td>tags</td>
        <td>image</td>
    </tr>
    @foreach (var im in Model.Images)
    {
        <tr class="image">
            @Html.Partial("Image", im)
            @Html.Partial("ImageControl", im)
        </tr>
    }
</table>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="~/js/jquery.tablesorter.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>
    
</head>
<body>
    <header>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <hr />
            <form action="/search" method="post">
                <input type="text" name="term" id="term" placeholder="search" />
                <button type="submit" class="btn btn-primary">Search</button>
            </form>
            <form action="/massadd" method="post">
                <input type="text" name="baseDir" id="baseDir" placeholder="path" />
                <button type="submit" class="btn btn-primary">MassAdd</button>
            </form>
            <form action="/image/search" method="post">
                <input type="text" name="term" id="imageterm" placeholder="image search" />
                <button type="submit" class="btn btn-primary">Imgsearch</button>
            </form>
            <div class="navigation">

                @Html.ActionLink("List", "List", "Admin")
                @Html.ActionLink("P", "ListPublished", "Admin")
                @Html.ActionLink("UP", "ListUnpublished", "Admin")
                @Html.ActionLink("ListAll", "ListAll", "Admin")
                @Html.ActionLink("TagList", "TagList", "Admin")
                @Html.ActionLink("Create", "CreateArticle", "Admin")
                <br />
                @Html.ActionLink("Upload Image", "UploadGet", "Image")
                @Html.ActionLink("List Images", "ViewImages", "Image")
                <br />@Html.ActionLink("Publications", "Index", "Publication")
                @Html.ActionLink("RP", "RandomPublished", "Admin")
                @Html.ActionLink("RU", "RandomUnpublished", "Admin")
                <form action="/publish" method="post">
                    <button type="submit" class="btn btn-primary">Publish All</button>
                </form>
            </div>
            @RenderBody()


        </main>
    </div>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site-local.js" asp-append-version="true"></script>
    <script src="~/js/site-public.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>